version: '2'

services:

  db:
    image: mysql:5.7
    container_name: mysql-test
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: counter
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pwd
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'